export default [
  // {
  //   path: '/user',
  //   layout: false,
  //   routes: [
  //     {
  //       path: '/user',
  //       redirect: '/user/login',
  //     },
  //     {
  //       path: '/user/login',
  //       layout: false,
  //       name: 'login',
  //       component: './user/login',
  //       locale: false,
  //     },
  //     {
  //       component: '404',
  //     },
  //   ],
  // },

  {
    path: '/',
    redirect: '/language',
  },

  {
    path: '/language',
    name: '多语言设置',
    component: './language-manage',
    key: 'language',
    access: 'normalRouteFilter',
    locale: false,
  },

  {
    path: '/007_users',
    name: '用户管理',
    locale: 'User Management',
    component: './user-manage/007',
    key: '007_users',
    access: 'normalRouteFilter',
  },
  {
    path: '/company',
    name: '公司管理',
    component: './company-manage',
    key: 'company',
    access: 'normalRouteFilter',
    locale: 'Company Management',
  },
  {
    path: '/major-match',
    name: '重点赛事',
    component: './major-match-manage',
    key: 'major-match',
    access: 'normalRouteFilter',
    locale: 'Major Match',
  },
  {
    path: '/tips',
    name: 'Tips',
    locale: 'Tips',
    component: './tips-manage',
    key: 'tips',
    access: 'normalRouteFilter',
  },
  {
    path: '/007_banner',
    name: 'Banner',
    component: './007_banner',
    key: '007_banner',
    locale: 'Banner Management',
    access: 'normalRouteFilter',
  },
  {
    path: '/007_data',
    name: 'Data',
    component: './007_data',
    key: '007_data',
    access: 'normalRouteFilter',
    locale: 'Data',
  },
  {
    path: '/expert',
    name: '专家管理',
    component: './expert-manage',
    key: 'expert',
    access: 'normalRouteFilter',
    locale: false,
  },
  {
    path: '/scheme',
    name: '方案管理',
    component: './scheme-manage',
    key: 'scheme',
    access: 'normalRouteFilter',
    locale: false,
  },
  {
    path: '/version',
    name: '版本管理',
    component: './version-manage',
    key: 'version',
    access: 'normalRouteFilter',
    locale: false,
  },
  {
    path: '/feedback',
    name: '反馈后台',
    component: './feedback-manage',
    key: 'feedback',
    access: 'normalRouteFilter',
    locale: false,
  },
  {
    path: '/preview',
    name: '预览页面',
    hideInMenu: true,
    component: './preview',
    key: 'preview',
    // access: 'normalRouteFilter',
  },
  {
    name: '403',
    path: '/403',
    hideInMenu: true,
    component: './exception/403',
    locale: false,
  },
  {
    component: './exception/404',
  },
];
